---
layout: page
title: "Contact Us!"
execute:
  freeze: false  # never re-render during project render
engine: knitr 
resources:
  - "application-2025.pdf"
app:
  pdf: "application-2025.pdf"
---

## CENS Mailing List
Please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSd39dw4zWNiIuS-AqcjwaGuXWSEqSLBvPsx_NCJC8D492tTeA/viewform?usp=dialog) to be added to our email list. 

## Collaborate with CENS
Do you have an event or opportunity for students and early career statisticians? We would love to advertise your event or opportunity to our members! Email [enar.cens@gmail.com](enar.cens@gmail.com) with information about your organization and opportunity, and we will be in touch discuss collaboration opportunities. 

## Join CENS
We are recruiting new members! Each member is appointed to a 2-year term. Within CENS, three or four people are chosen to participate in the steering committee, which reports to the RAB chair. Members of the steering committee will serve an additional year on CENS. CENS members will meet in person yearly at the ENAR Spring Meeting and participate in conference calls throughout the year to plan events and address issues as they arise. If you are interested in joining CENS, please fill out the application below and send to [enar.cens@gmail.com](enar.cens@gmail.com) by June 16, 2025.

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}
.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg app-download" href="`r rmarkdown::metadata$app$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download the application!
  </a>
</p>
<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$app$pdf`#toolbar=0" style="border: 0.5px;width: 100%;"></iframe>
</div>
```

