---
title: About
---

## Members and Goals

The **Council for Emerging and New Statisticians (CENS)** was formed in 2012 by ENAR's Regional Advisory Board (RAB) to help ENAR better address the needs of all students and recent graduates. CENS is composed of 10 graduate students, post-doctoral fellows, or recent graduates, who are ENAR members from academia, government, or private industry. With the help of the RAB Liaison, CENS members collaborate to:

-   Bring student/recent graduate concerns to the attention of RAB and ENAR,

-   Work to help ENAR better serve all students/recent graduates,

-   Advise and help implement ideas to enhance the benefits of ENAR membership and to increase awareness of the benefits of ENAR membership to students,

-   Organize a CENS session at each ENAR Spring Meeting,

-   Assist in planning events that help advance students' and recent graduates\' education and careers,

-   Contribute to the development of ENAR\'s social media presence.

------------------------------------------------------------------------

## Mission

CENS seeks to advocate for the needs and concerns of students and recent graduates in collaboration with ENAR’s Regional Advisory Board. Through annual events at the ENAR Spring Meeting, CENS strives to promote the benefits of participating in the ENAR community, support the advancement of students and recent graduates, and facilitate stronger connections within the statistical community.

------------------------------------------------------------------------

## Testimonials

"CENS rocks!"

Former member 1 - Former member's current position

"I Love CENS!"

Current member 1 - Current member's current position

"CENS is fantastic and we love them!"

ENAR leadership member 1 - leader's current role
