---
title: Paths to Success - Perspectives from Recruiters and Hiring Committees with a Focus on Fostering Inclusivity and Equity
---

The transition from graduate school to navigate the unknowns of the job market is challenging for every new statistician. Proper training, efficient networking, and building a professional profile are some of the early initiatives to prepare graduate students for this change. Statisticians are trained in modeling and data analysis; however, the real-world job market requires skills beyond technical knowledge, including communication, presentation, leadership, and collaborative skills, as well as pitching one's ideas and goals, and being able to advocate for oneself. As a group of emerging statisticians, CENS would like to fill this gap and invite academia and industry statisticians to discuss the unique challenges that early-career statisticians might face in a new work environment and how to deal with them.

This session aims to provide valuable guidance and insights to empower students on their career journey. With a special focus on the preparation of diversity statements as well as diverse work environment, this session recognizes the importance of fostering inclusivity and diversity in the statistics and biostatistics field. Attendees will gain practical strategies and tools to effectively communicate their experiences, perspectives, and commitment to diversity. By addressing the unique challenges faced by underrepresented groups, this session aims to create a supportive environment that promotes equity and equal opportunities.

Through interactive discussions and real-life examples, attendees will explore diverse career pathways, learn about industry expectations, and acquire skills to effectively market themselves. Our panel includes both academic and industry statisticians who have served on hiring committees. Their valuable insights and mentoring guidance will be useful for newly emerging statisticians for navigating the job market successfully.

Topics to be discussed include, but are not limited to, crafting an effective diversity statement, navigating funding opportunities, exploring the similarities and differences between industry and academia jobs, perspectives of recruiters or hiring committees, what questions should be prepared in an interview, and how to prepare for an interview. Panelists will share their experiences and provide guidance. We anticipate attendees will leave this session equipped with tools to succeed in their initial job search and be better informed about the opportunities to achieve their career goals.
