---
title: Converting AI from a Buzzword to a Tangible Skill - Dos and Don’ts for Early-Career Statisticians
---

AI skills are fashionable to include on a resume or CV, but what AI-related skills truly matter for early-career biostatisticians? As students and recent graduates enter careers that demand AI-related knowledge, it is crucial that AI is not just a buzzword in a job application. Statisticians require guidance on the tangible AI skills that will enhance their careers in industry, academia, government, and beyond. Given this need, ENAR’s Council for Emerging and New Statisticians (CENS) is providing a panel session featuring four experts with various roles and experience implementing AI. The discussion will cover three central themes: AI as a skill for statistical analysis, AI as a skill for improving productivity and workflows, and AI as a means for showcasing skills and accomplishments. Our panelists will expound on best practices, ethical considerations, and resources that early-career statisticians could use to advance their AI-related skills. Panelists will specifically consider that our audience may contain many who have little to no experience with the topics and ensure that the discussion remains accessible to our broad target audience, regardless of their experience level.