---
title: Beyond Academia - Exploring Statistics Careers in Industry, Government, and More
---

In today's rapidly evolving data-driven world, the skills of statisticians extend far beyond traditional academic research. From influencing policy decisions in government agencies to driving innovation at technology companies, the range of opportunities for statisticians is expanding quickly. Despite the abundance of opportunities, their variety and scope are not always well communicated to graduate students and early-career statisticians, who often have limited exposure beyond academic settings at this point in their careers. As an advocacy group for early-career statisticians, our panel session is designed to illuminate the diverse career opportunities available in various sectors beyond traditional academic pathways. We hope this session can motivate early career statisticians to explore a wide array of career options aligned with their interests and understand how to navigate these varied roles. By showcasing insights from professionals across different industries, we aim to bridge the gap between academic training and the dynamic, multifaceted career landscape available outside of academia.

Statisticians are integral to various sectors, playing pivotal roles in extracting valuable insights from data, conveying these findings to relevant stakeholders, making critical decisions, and even building data-driven products. Despite the burgeoning opportunities, the distinctions between these roles can be unclear, and the path to these positions often diverges significantly from traditional academic trajectories. This session aims to explore the diverse career paths available to statisticians beyond academia, offering guidance and inspiration for those seeking to make meaningful contributions in non-academic fields.

To achieve our session goals, we will feature a diverse panel of six statisticians from various career stages with experience in government, non-profits, technology, sports, academia, and pharmaceuticals. Each panelist will share their unique experiences and insights from their respective career paths and current positions. This discussion will highlight the different ways that statistics are applied across these industries and provide practical advice on the skills needed for each sector.

As session organizers, we represent a group of emerging and new statisticians from the Council for Emerging and New Statisticians (CENS) within ENAR (the Eastern North American Region of the International Biometrics Society), and this session aligns with the goals of our group to support emerging statisticians in their career journeys. We have previously organized many invited panel sessions, including annually at ENAR (since 2016) and JSM (since 2020) conferences.

The Chair will begin the session by briefly introducing CENS and its goals for helping ENAR better serve the needs of students and recent graduates. Next, panelists will each give a short introduction about their background, interests, and experiences exploring different career pathways. The chair will then moderate a discussion on the topics listed above, including why the panelist chose their path, what they enjoy about their work, what they find challenging, advice they have for new statisticians, skills needed for their job, and other audience-driven topics of interest. The majority of the session will consist of open Q&A during which time our speakers can answer any questions attendees may have.