---
title: Connecting for Impact - Social Media, Coffee Chats, and Beyond

---

Strong professional connections are the foundation of impactful careers in statistics. This session will explore how students and early career statisticians can build and leverage networks to create opportunities, foster collaborations, and, ultimately, contribute to societal good. In today's professional world, social media and (often online) coffee chats offer opportunities for connection. Our session will share how students and early-career professionals can harness these casual interactions to build creative alternative strategies and form meaningful professional relationships and lasting mentorships. 

This panel will feature five statisticians from various career stages with experience in education, social enterprises, academia, consulting, and industry. Each panelist will share their networking-related experiences and insights unique to their respective career paths and current positions. The discussion will highlight the different ways statisticians network within and beyond their own community. We will also focus on how the panelists have utilized their networks to develop and carry out meaningful projects with social impact.

As session organizers, we represent the Council for Emerging and New Statisticians (CENS) within ENAR (the Eastern North American Region of the International Biometrics Society), and this session aligns with the group’s goals of supporting emerging statisticians in their career journeys. We have sponsored a variety of well-attended invited panel sessions, including annual events at conferences such as ENAR (since 2016) and JSM (since 2020). With the mission of advocating for the needs and concerns of students and recent graduates in mind, we propose this session to cater to this audience for guidance on connecting with peers and making your presence known as an early career statistician.

The co-chairs will begin the session by briefly introducing CENS and its goals of addressing the needs of students and recent graduates. Panelists will be prompted to each give a short introduction about their background, interests, and experiences with networking and career building. The chairs will then moderate a discussion on the above topics, including how panelists built their networks throughout their careers, what they found challenging and rewarding with the process, and advice they have for new statisticians. Prompts will also focus on how panelists leverage their projects for social impact and other audience-driven topics of interest. The majority of the session will consist of open Q&A, during which time our speakers can answer any questions attendees may have.
