---
title: Crafting Relevant Research - Informative and Translational Statistics for Public Policy
---

Translating statistics into a simple and informative narrative for the public can be particularly challenging for statisticians at an early stage in their career. As an advocacy group for early-career statisticians, our panel session aims to help recent graduates and early-career statisticians, especially those who are interested in collaborative research in policy fields, learn essential skills in communicating statistics with policy stakeholders as well as strategies of identifying collaboration opportunities and maintaining good collaboration in policy fields. We hope this session can also motivate early career statisticians to engage in collaborative work within policy fields and use scientific findings from their research to help improve policy decision making.

Informative and translational statistics play crucial roles in shaping effective public policy by providing valuable insights, evidence-based decision-making, and clear communication to policymakers and the public. Informative statistics involves the analysis and interpretation of data to extract meaningful insights. Translational statistics involves transforming complex statistical findings into actionable insights that are easily understandable by policymakers, stakeholders, and the general public. These two aspects of statistics help bridge the gap between data analysis and the formulation of policies that can address societal challenges and promote the well-being of communities thus countering misinformation and its spread. To accomplish such objectives, statisticians play a crucial role in extracting insightful findings from data and conveying them for the comprehension of both policy makers and the general public. However, these responsibilities can be particularly challenging for statisticians in the early stages of their career.